language: php
php:
  - 7.1
sudo: false
matrix:
  allow_failures:
    - php: 7.1
install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - composer install

script:
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
    - travis_retry php vendor/bin/coveralls
    # or enable logging
    - travis_retry php vendor/bin/coveralls -v
